import { Product, Category, DiscountCode } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'all', name: 'All Items', icon: '📋' },
  { id: 'coffee', name: 'Coffee & Drinks', icon: '☕' },
  { id: 'tea', name: 'Teas & Matchas', icon: '🍵' },
  { id: 'bakery', name: 'Bakery & Grains', icon: '🥐' },
  { id: 'lunch', name: 'Greens & Sandwiches', icon: '🥗' },
  { id: 'merch', name: 'Sweets & Merch', icon: '🏷️' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Single Origin Espresso',
    price: 3.50,
    category: 'coffee',
    stock: 25,
    maxStock: 30,
    color: 'bg-amber-50 border-amber-200 text-amber-900',
    icon: '☕',
    code: '1001',
    imageUrl: 'espresso-waves',
  },
  {
    id: 'prod-2',
    name: 'Cardamom Oat Latte',
    price: 5.75,
    category: 'coffee',
    stock: 18,
    maxStock: 25,
    color: 'bg-amber-50 border-amber-200 text-amber-900',
    icon: '🥛',
    code: '1002',
    imageUrl: 'oat-latte-stripes',
  },
  {
    id: 'prod-3',
    name: 'Espresso Tonic',
    price: 4.85,
    category: 'coffee',
    stock: 12,
    maxStock: 15,
    color: 'bg-amber-50 border-amber-200 text-amber-900',
    icon: '🥤',
    code: '1003',
    imageUrl: 'tonic-bubbles',
  },
  {
    id: 'prod-4',
    name: 'Ceremonial Stone Matcha',
    price: 6.00,
    category: 'tea',
    stock: 20,
    maxStock: 25,
    color: 'bg-emerald-50 border-emerald-200 text-emerald-900',
    icon: '🍵',
    code: '2001',
    imageUrl: 'matcha-grid',
  },
  {
    id: 'prod-5',
    name: 'Organic Jasmine Pearls',
    price: 4.50,
    category: 'tea',
    stock: 15,
    maxStock: 20,
    color: 'bg-emerald-50 border-emerald-200 text-emerald-900',
    icon: '🍃',
    code: '2002',
    imageUrl: 'jasmine-spiral',
  },
  {
    id: 'prod-6',
    name: 'Hibiscus Iced tea',
    price: 4.25,
    category: 'tea',
    stock: 5, // low stock!
    maxStock: 20,
    color: 'bg-emerald-50 border-emerald-200 text-emerald-900',
    icon: '🌺',
    code: '2003',
    imageUrl: 'hibiscus-blossom',
  },
  {
    id: 'prod-7',
    name: 'Sourdough Butter Croissant',
    price: 4.25,
    category: 'bakery',
    stock: 8,
    maxStock: 20,
    color: 'bg-orange-50 border-orange-200 text-orange-900',
    icon: '🥐',
    code: '3001',
    imageUrl: 'croissant-swirl',
  },
  {
    id: 'prod-8',
    name: 'Everything Seeded Bagel',
    price: 4.95,
    category: 'bakery',
    stock: 14,
    maxStock: 15,
    color: 'bg-orange-50 border-orange-200 text-orange-900',
    icon: '🥯',
    code: '3002',
    imageUrl: 'bagel-seeds',
  },
  {
    id: 'prod-9',
    name: 'Wild Blueberry Frangipane',
    price: 5.50,
    category: 'bakery',
    stock: 0, // Out of stock!
    maxStock: 10,
    color: 'bg-orange-50 border-orange-200 text-orange-900',
    icon: '🥧',
    code: '3003',
    imageUrl: 'frangipane-tart',
  },
  {
    id: 'prod-10',
    name: 'Heirloom Avocado Toast',
    price: 12.50,
    category: 'lunch',
    stock: 10,
    maxStock: 12,
    color: 'bg-lime-50 border-lime-200 text-lime-900',
    icon: '🥑',
    code: '4001',
    imageUrl: 'avocado-grid',
  },
  {
    id: 'prod-11',
    name: 'Smoked Salmon Club',
    price: 14.00,
    category: 'lunch',
    stock: 6,
    maxStock: 10,
    color: 'bg-lime-50 border-lime-200 text-lime-900',
    icon: '🥪',
    code: '4002',
    imageUrl: 'salmon-mesh',
  },
  {
    id: 'prod-12',
    name: 'Nordic Beet & Feta Salad',
    price: 11.25,
    category: 'lunch',
    stock: 7,
    maxStock: 10,
    color: 'bg-lime-50 border-lime-200 text-lime-900',
    icon: '🥗',
    code: '4003',
    imageUrl: 'beet-salad-polka',
  },
  {
    id: 'prod-13',
    name: 'Double Fudge Miso Cookie',
    price: 3.75,
    category: 'merch',
    stock: 22,
    maxStock: 30,
    color: 'bg-purple-50 border-purple-200 text-purple-900',
    icon: '🍪',
    code: '5001',
    imageUrl: 'cookie-sparks',
  },
  {
    id: 'prod-14',
    name: 'Ceramic KeepCup (12oz)',
    price: 28.00,
    category: 'merch',
    stock: 10,
    maxStock: 10,
    color: 'bg-purple-50 border-purple-200 text-purple-900',
    icon: '🥛',
    code: '5002',
    imageUrl: 'keepcup-circles',
  },
  {
    id: 'prod-15',
    name: 'Roaster Blend Coffee (250g)',
    price: 19.50,
    category: 'merch',
    stock: 15,
maxStock: 15,
    color: 'bg-purple-50 border-purple-200 text-purple-900',
    icon: '🎒',
    code: '5003',
    imageUrl: 'roaster-stripes',
  },
];

export const DISCOUNT_CODES: DiscountCode[] = [
  { code: 'COFFEE10', type: 'percent', value: 10 },
  { code: 'SAVEFIVE', type: 'fixed', value: 5.00, minSubtotal: 15.00 },
  { code: 'SPRING20', type: 'percent', value: 20 },
  { code: 'STAFF50', type: 'percent', value: 50 },
];

export const TAX_RATE = 0.0825; // 8.25% Sales Tax
export const DEFAULT_CASHIER = 'Maisie Clarke';
